project04/config/routes.rb
Articles::Application.routes.draw do
  resources :world_articles

  root to: 'world_articles#index', as: 'world_articles'

end

project04/app/models/world_article.rb
class WorldArticle < ActiveRecord::Base
  validates_presence_of :title, :author, :body
end

project04/app/controllers/world_articles_controller.rb
class WorldArticlesController < ApplicationController
  # GET /world_articles
  # GET /world_articles.json
  def index
    @world_articles = WorldArticle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @world_articles }
    end
  end

  # GET /world_articles/1
  # GET /world_articles/1.json
  def show
    @world_article = WorldArticle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @world_article }
    end
  end

  # GET /world_articles/new
  # GET /world_articles/new.json
  def new
    @world_article = WorldArticle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @world_article }
    end
  end

  # GET /world_articles/1/edit
  def edit
    @world_article = WorldArticle.find(params[:id])
  end

  # POST /world_articles
  # POST /world_articles.json
  def create
    @world_article = WorldArticle.new(params[:world_article])

    respond_to do |format|
      if @world_article.save
        format.html { redirect_to @world_article, notice: 'World article was successfully created.' }
        format.json { render json: @world_article, status: :created, location: @world_article }
      else
        format.html { render action: "new" }
        format.json { render json: @world_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /world_articles/1
  # PUT /world_articles/1.json
  def update
    @world_article = WorldArticle.find(params[:id])

    respond_to do |format|
      if @world_article.update_attributes(params[:world_article])
        format.html { redirect_to @world_article, notice: 'World article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @world_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /world_articles/1
  # DELETE /world_articles/1.json
  def destroy
    @world_article = WorldArticle.find(params[:id])
    @world_article.destroy

    respond_to do |format|
      format.html { redirect_to world_articles_url }
      format.json { head :no_content }
    end
  end
end

project04/app/helpers/world_articles_helper.rb
module WorldArticlesHelper
end

project04/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articl.es -- All the World's Articles (with a name .com hipsters love)</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<h1>Articl.es</h1>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>

project04/app/views/world_articles/_form.html.erb
<%= form_for(@world_article) do |f| %>
  <% if @world_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@world_article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @world_article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body , rows: 15%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project04/app/views/world_articles/edit.html.erb
<h3>... my cousin works for Bit.ly</h3>

<h1>Editing "<%= @world_article.title %>"</h1>

<%= link_to image_tag("arrow_left.png", title: 'Article List') + 'back', world_articles_path %>
<%= render 'form' %>

project04/app/views/world_articles/index.html.erb
<h3>...with a name .com that hipsters love!</h3>


<table>
  <tr>
	<td class="header"><h1>All the World's Articles</h1></td>
	<td class="header"><%= link_to image_tag("add.png", :title => 'Create New Article') + 'Create an article', new_world_article_path %></td>
  </tr>
</table>
<table>
  <tr>
    <th class="list_title">Title</th>
    <th class="list_author">Author</th>
    <th class="list_body">Body</th>
    <th class="list_creation_date">Creation Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% article_inc=0 %>
<% @world_articles.each do |world_article| %>
  <tr class="<%= cycle('list_line_even','list_line_odd') %>">
    <td class="list_title"><%= world_article.title %></td>
    <td class="list_author"><%= world_article.author %></td>
    <td class="list_body">
		<% if world_article.body.size > 50 %>
			<%= world_article.body[0..50] + '...'%>
		<% else %>
			<%= world_article.body %>
		<% end %>
	</td>
	<td class="list_creation_date"><%= world_article.created_at.strftime("%a, %b. %d %Y") %></td>
    <td><%= link_to image_tag("magnifier.png", :title => 'View'), world_article %></td>
    <td><%= link_to image_tag("page_edit.png", :title => 'Edit'), edit_world_article_path(world_article) %></td>
    <td><%= link_to image_tag("bin_empty.png", :title => 'Delete'), world_article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% article_inc = article_inc + 1 %>
<% end %>
</table>
<% if article_inc == 1 %>
	<%= raw article_inc %> Article
<% else %>
	<%= raw article_inc %> Articles
<% end %>

<br />

<%= link_to 'New World article', new_world_article_path %>

project04/app/views/world_articles/new.html.erb
<h3>... not just for the country of spain</h3>

<%= render 'form' %>

<%= link_to 'Back', world_articles_path %>

project04/app/views/world_articles/show.html.erb
<h3>... what's "articl" in Spanish anyway?</h3>
<p id="notice"><%= notice %></p>
<table>
<tr>
<td><%= link_to image_tag("arrow_left.png", :title => "List all articles") + "List all articles", world_articles_path %></td>
<td><%= link_to image_tag("page_edit.png", :title => 'Edit'), edit_world_article_path(@world_article) %></td>
<td><%= link_to image_tag("bin_empty.png", :title => 'Delete'), @orld_article, confirm: 'Are you sure?', method: :delete %></td>
<td><%= link_to image_tag("magnifier.png", :title => 'Email'), @world_article %></td><!-- Need to get a email picture and figure out the functionality -->
</tr>
</table>

<p>
  <b>
  <%= @world_article.title %>
  </b>
</p>

<p>
  by <%= @world_article.author %>, # edits since <%= @world_article.created_at.strftime("%b. %d %Y") %>
</p>

<p>
  <%= @world_article.body %>
</p>